import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { fetchIndex, repoIsConfigured } from "../lib/api.js";

export default function IndexPage() {
  const [state, setState] = useState({ status: "loading", data: null, error: null });

  useEffect(() => {
    if (!repoIsConfigured()) {
      setState({ status: "unconfigured", data: null, error: null });
      return;
    }
    fetchIndex()
      .then((data) => setState({ status: "ready", data, error: null }))
      .catch((err) => setState({ status: "error", data: null, error: err.message }));
  }, []);

  if (state.status === "unconfigured") {
    return (
      <div className="max-w-reading">
        <p className="font-display text-xl text-ink-soft">
          Configure your repository to see digests.
        </p>
      </div>
    );
  }

  if (state.status === "loading") {
    return <p className="font-mono text-sm text-muted">Loading digests…</p>;
  }

  if (state.status === "error") {
    return (
      <div className="max-w-reading">
        <p className="font-display text-xl text-accent">
          Couldn't fetch digests.
        </p>
        <p className="text-sm text-muted mt-2 font-mono">{state.error}</p>
        <p className="text-sm text-muted mt-4">
          If the repo is private, the dashboard can't read it via raw URLs.
          Make the repo public or move the dashboard behind a server.
        </p>
      </div>
    );
  }

  const digests = state.data || [];

  if (digests.length === 0) {
    return (
      <div className="max-w-reading">
        <p className="font-display text-xl text-ink-soft">
          No digests yet.
        </p>
        <p className="text-muted mt-3">
          Run <code className="font-mono text-sm bg-paper-dim px-1.5 py-0.5">
            python fertility_litmonitor.py --years 5
          </code> in the <code className="font-mono text-sm">litmonitor</code> directory,
          commit, and they'll appear here.
        </p>
      </div>
    );
  }

  return (
    <div className="max-w-3xl">
      <p className="text-muted mb-10 max-w-reading">
        A weekly read of the fertility literature, filtered to the questions that
        matter for the case. Each digest below is generated by the GitHub Action
        from the previous week's PubMed activity.
      </p>

      <ol className="space-y-0">
        {digests.map((d, i) => (
          <DigestRow key={d.filename} digest={d} index={i} />
        ))}
      </ol>
    </div>
  );
}

function DigestRow({ digest, index }) {
  const date = digest.digest_date || "(unknown date)";
  const count = digest.paper_count || 0;
  const isLatest = index === 0;
  const topicCount = Object.keys(digest.topic_counts || {}).length;

  return (
    <li className="hairline first:border-t-0 py-6 md:py-7 group">
      <Link
        to={`/digest/${digest.filename}`}
        className="grid grid-cols-[auto_1fr_auto] gap-x-6 md:gap-x-10 items-baseline"
      >
        <span className="font-mono text-xs text-muted-soft tabular-nums w-12">
          {String(index + 1).padStart(2, "0")}
        </span>

        <div className="min-w-0">
          <h2 className="font-display text-2xl md:text-3xl font-medium leading-tight tracking-tight group-hover:text-accent transition-colors">
            {date}
            {isLatest && (
              <span className="ml-3 align-middle text-xs uppercase tracking-smallcaps text-accent font-mono font-medium">
                latest
              </span>
            )}
          </h2>
          <p className="smallcaps mt-2">
            {count} {count === 1 ? "paper" : "papers"}
            {topicCount > 0 && ` · ${topicCount} ${topicCount === 1 ? "topic" : "topics"}`}
            {digest.mode && ` · ${digest.mode}`}
          </p>
        </div>

        <span className="font-mono text-muted text-sm hidden md:inline opacity-0 group-hover:opacity-100 transition-opacity">
          read →
        </span>
      </Link>
    </li>
  );
}
